services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: songy_wongy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432' # Keep for local development
      - '5342:5432' # Additional port for Docker database access
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - songy_wongy_net
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - songy_wongy_net
  app:
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile.dev
      args:
        APP: api
    ports:
      - '8000:8000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # Only override database URL for Docker networking
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/songy_wongy_db
    working_dir: /app
    command: yarn workspace api start:dev
    volumes:
      - ../../:/app

    networks:
      - songy_wongy_net

networks:
  songy_wongy_net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
