services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: songy_wongy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - songy_wongy_net
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - songy_wongy_net
  app:
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
      args:
        APP: api
    ports:
      - '8000:8000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/songy_wongy_db
      - REDIS_URL=redis://redis:6379
      - BETTER_AUTH_SECRET=dev-secret-change-me
    working_dir: /app
    command: yarn workspace api start:dev
    volumes:
      - ../../:/app

    networks:
      - songy_wongy_net

networks:
  songy_wongy_net:
    driver: bridge

volumes:
  postgres_data:
